### PR TITLE
perf(useResizeColumns): optimize dispatch count

### PR DESCRIPTION
**Pull request by theopak**
👋 hey internet, here's an optimization that significantly improves column resize performance

- i'm consistently seeing a 30-50% reduction in the number of calls to `dispatch()` when i interactively drag the handle back and forth in the "column-resizing" demo
- want to debug this even farther locally or on codesandbox?
  - this commit demonstrates how to add some console statements to show the number of calls: 37a69f5
  - you can pull this branch and revert that commit to measure this interactively yourself if you want to
- partially addresses #3165

### CODE REVIEW

**Comment by bhefter** [comment]
👍 I tested this locally and was able to log notably fewer dispatch calls and no noticeable side effects

**Comment by theopak** [comment]
hey! @tannerlinsley please lmk if there's anything else you want to see to help review this pr

**Comment by subhamayd2** [comment]
This works perfectly. Hope this gets merged soon.

**Comment by FezVrasta** [comment]
What's the plan to get this merged and released? Anything we can do to help with it?

**Comment by megastas** [comment]
Guys, why still not merged?

**Comment by theopak** [comment]
> hey! @tannerlinsley please lmk if there's anything else you want to see to help review this pr

polite bump!

**Comment by FezVrasta** [comment]
😢

**Comment by tannerlinsley** [comment]
I'll reopen this if anyone wants to do the research on how supported RAF is without a polyfill

**Comment by FezVrasta** [comment]
> I'll reopen this if anyone wants to do the research on how supported RAF is without a polyfill

IE10+

**Comment by tannerlinsley** [comment]
Good enough for me.

**Comment by tannerlinsley** [comment]
Before I can merge this, I need to set up my semantic release to handle other branches/ previous versions.

**Pull request merged**
