### PR TITLE
fix: remove react from core

### PR DESCRIPTION
**Pull request by izznatsir**
Remove `react` from `table-core` to make it truly framework agnostic in terms of event types and event handling.

### Testing
All tests pass. The examples also run without problem.

### CODE REVIEW

**Comment by tannerlinsley** [comment]
I worry about removing some of those persist calls. We need the data that gets persisted to do a lot of internal things that wouldn't be there if we didn't persiste them.

**Comment by izznatsir** [comment]
The persist calls are not removed, it simply removed from the type and only call it when it exist.

**Comment by tannerlinsley** [comment]
Gotcha. Well, if you can fixup the conflicts, I'll merge. :)

**Comment by izznatsir** [comment]
Conflicts resolved.

**Pull request merged**
