### PR TITLE
fix(useResizeColumns):fixed rtl layout by reverseResizer prop

### PR DESCRIPTION
**Pull request by RezaHeydarii**
by adding this this optional prop to the useTable hook the resizer in the rtl layouts works just like ltr layouts , also we may have the reverse behaviour of resizer as well .

reverseResizer prop added to useTable hook witch is used in useResizeColumns

### CODE REVIEW

**Comment by gauravsbagul** [comment]
Hi @RezaHeydarii, I need this feature in y project, But since PR is not yet merged ow do I used this?

**Comment by RezaHeydarii** [comment]
Hello @gauravsbagul , this feature was essential in our project too ... so i user [https://www.npmjs.com/package/patch-package](url) to add my changes to the react table and it worked just fine as a temp solution.

**Comment by gauravsbagul** [comment]
Will try that, thanks.

**Comment by tannerlinsley** [comment]
This is a good addition, but really needs to have conflicts resolved and all of the build artifacts removed from the PR. If you would rather open a new PR and start fresh, feel free to close and do that.

**Comment by tannerlinsley** [comment]
Feel free to reopen without all of the untracked change files, etc.

**Pull request closed without merging**
